import type { Destination } from "@/domain/destination/destination.types";
import type { Tour } from "@/domain/tour/tour.types";

export const MOCK_DESTINATIONS: Destination[] = [
  {
    id: "dest-spiti",
    slug: "spiti-valley",
    name: "Spiti Valley",
    region: "Trans-Himalayas",
    description:
      "A high-altitude cold desert valley carved by the Spiti River. Home to thousand-year-old cliffside monasteries, fossil villages, high mountain passes, and the azure waters of Chandratal.",
    heroImage: "https://images.unsplash.com/photo-1581793745862-99fde7fa73d2?auto=format&fit=crop&w=1600&q=80",
    heroImageId: null,
    highlights: [
      "Key Monastery (4,166m)",
      "Chandratal Lake (The Moon Lake)",
      "Pin Valley National Park",
      "Dhankar cliff monastery",
      "Kibber & Komic (world's highest villages)",
    ],
    seoTitle: "Spiti Valley Tours & Road Expeditions | Fayul Retreat",
    seoDesc: "Explore curated private tours across Spiti Valley. Monasteries, homestays, Chandratal, and Kunzum Pass.",
    isPublished: true,
    sortOrder: 1,
    toursCount: 2,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "dest-kinnaur",
    slug: "kinnaur",
    name: "Kinnaur Valley",
    region: "Lower Himalayas",
    description:
      "Where lush cedar forests meet stark vertical granite peaks. Sacred to both Hindus and Buddhists, famed for the Kinnaur Kailash circuit and the ancient border village of Chitkul.",
    heroImage: "https://images.unsplash.com/photo-1605649487212-47bdab064df8?auto=format&fit=crop&w=1600&q=80",
    heroImageId: null,
    highlights: [
      "Kinnaur Kailash sacred peak view",
      "Chitkul — last Indian village on Tibet border",
      "Sangla Valley apple orchards",
      "Kalpa golden hour over peaks",
      "Kamru Fort heritage",
    ],
    seoTitle: "Kinnaur Valley Treks & Private Journeys | Fayul Retreat",
    seoDesc: "Handcrafted journeys to Kinnaur, Kalpa, and Sangla Valley from Shimla.",
    isPublished: true,
    sortOrder: 2,
    toursCount: 1,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "dest-shimla",
    slug: "shimla",
    name: "Shimla & Shivaliks",
    region: "Himachal Heartland",
    description:
      "The summer capital of British India, set amid dense deodar forests at 2,205m. Walk heritage trails, explore apple belts of Narkanda, and relax at mountain retreats.",
    heroImage: "https://images.unsplash.com/photo-1597074866923-dc0589150358?auto=format&fit=crop&w=1600&q=80",
    heroImageId: null,
    highlights: [
      "UNESCO Kalka-Shimla Toy Train",
      "The Mall & Ridge heritage walk",
      "Jakhu Temple panoramic viewpoint",
      "Cedar forest walks in Mashobra",
      "Apple harvesting in Narkanda",
    ],
    seoTitle: "Shimla Heritage Tours & Boutique Retreats | Fayul Retreat",
    seoDesc: "Stay and explore Shimla with expert local guides and heritage stays.",
    isPublished: true,
    sortOrder: 3,
    toursCount: 1,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "dest-manali",
    slug: "manali-lahaul",
    name: "Manali & Lahaul",
    region: "Kullu & Pir Panjal",
    description:
      "From the pine-scented orchards of Old Manali to the high barren plateau of Lahaul via Atal Tunnel. Gateway to Rohtang Pass, Bhrigu Lake, and Sissu waterfalls.",
    heroImage: "https://images.unsplash.com/photo-1571401835393-8c5f35328320?auto=format&fit=crop&w=1600&q=80",
    heroImageId: null,
    highlights: [
      "Atal Tunnel gateway to Lahaul",
      "Rohtang Pass panoramic views",
      "Sissu waterfall & glacial lake",
      "Solang Valley adventure sports",
      "Old Manali cedar cafe trails",
    ],
    seoTitle: "Manali & Lahaul Valley Expeditions | Fayul Retreat",
    seoDesc: "Experience high-altitude expeditions and leisurely family stays in Manali.",
    isPublished: true,
    sortOrder: 4,
    toursCount: 1,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const MOCK_TOURS: Tour[] = [
  {
    id: "tour-spiti-circuit",
    slug: "spiti-valley-complete-circuit",
    title: "Spiti Valley Complete Circuit: Kinnaur, Kaza & Chandratal",
    travelStyle: "Trekking",
    durationDays: 10,
    minGroup: 2,
    maxGroup: 10,
    basePriceInr: 28500,
    summary:
      "The definitive high-altitude Himalayan road expedition. Travel from Shimla through the green valleys of Kinnaur, cross into the moonscapes of Spiti, visit ancient cliffside monasteries, and camp under the stars at Chandratal Lake.",
    highlights: [
      "Drive through the famous Hindustan-Tibet road gorge",
      "Sunset views of Kinnaur Kailash from Kalpa",
      "Walk through Chitkul — India's last inhabited village",
      "1,000-year-old Key & Dhankar cliff monasteries",
      "Send a postcard from Hikkim — world's highest post office (4,440m)",
      "Stargazing and camping at Chandratal Moon Lake (4,300m)",
      "Cross Kunzum Pass at 4,590m",
    ],
    inclusions: [
      "Private 4x4 / Tempo Traveller vehicle for the full circuit",
      "9 nights handpicked boutique homestays and eco-lodges",
      "1 night luxury Swiss tent camping at Chandratal with warm bedding",
      "Breakfast and dinners daily featuring organic regional cuisine",
      "Experienced local Himalayan driver-guide & oxygen cylinder support",
      "Inner line permits & entry fees for all valleys",
    ],
    exclusions: [
      "Airfare / Train tickets to/from Delhi or Chandigarh",
      "Lunches & personal shopping / gear rentals",
      "Travel & medical evacuation insurance",
    ],
    mapData: null,
    isPublished: true,
    isFeatured: true,
    sortOrder: 1,
    destination: {
      id: "dest-spiti",
      name: "Spiti Valley",
      slug: "spiti-valley",
      region: "Trans-Himalayas",
    },
    itineraryDays: [
      {
        id: "d1",
        dayNumber: 1,
        title: "Shimla to Narkanda & Rampur",
        description: "Depart Shimla winding through the pine forests of Fagu and apple orchards of Narkanda. Descend into the Sutlej valley to Rampur for acclimatization.",
        location: "Rampur",
        accommodation: "Riverside Lodge",
        meals: "Dinner",
        activities: ["Scenic drive", "Hatu Peak viewpoint"],
      },
      {
        id: "d2",
        dayNumber: 2,
        title: "Rampur to Sangla Valley & Chitkul",
        description: "Enter Kinnaur district along the dramatic cliff-carved roads. Reach Sangla Valley and continue to Chitkul, the last inhabited village on the Indo-Tibet border.",
        location: "Chitkul",
        accommodation: "Traditional Wooden Guesthouse",
        meals: "Breakfast, Dinner",
        activities: ["Baspa river walk", "Border village exploration"],
      },
      {
        id: "d3",
        dayNumber: 3,
        title: "Chitkul to Kalpa",
        description: "Morning walk by the glacial Baspa river. Drive up to Kalpa facing the sacred Kinnaur Kailash massif. Witness the evening golden glow over the snowy peaks.",
        location: "Kalpa",
        accommodation: "Apple Orchard Retreat",
        meals: "Breakfast, Dinner",
        activities: ["Suicide Point walk", "Hu-Bu-Lan-Kar monastery"],
      },
      {
        id: "d4",
        dayNumber: 4,
        title: "Kalpa to Nako Lake & Tabo Monastery",
        description: "Cross into Spiti at Sumdo. Explore the ancient high-altitude Nako sacred lake, then visit Tabo Monastery founded in 996 CE, known as the 'Ajanta of the Himalayas'.",
        location: "Tabo",
        accommodation: "Monastery Guesthouse",
        meals: "Breakfast, Dinner",
        activities: ["10th-century fresco tour", "Nako village prayer wheels"],
      },
      {
        id: "d5",
        dayNumber: 5,
        title: "Tabo to Dhankar & Pin Valley to Kaza",
        description: "Ascend to Dhankar Monastery perched dramatically above the confluence of Spiti and Pin rivers. Explore the wildlife habitat of Pin Valley before reaching Kaza.",
        location: "Kaza",
        accommodation: "Boutique Eco Hotel",
        meals: "Breakfast, Dinner",
        activities: ["Dhankar Lake trek", "Pin Valley national park"],
      },
      {
        id: "d6",
        dayNumber: 6,
        title: "Kaza High Villages: Key, Kibber, Hikkim & Komic",
        description: "Visit Key Monastery (4,166m). Drive to Kibber, Langza (fossil village with giant Buddha statue), and post a card at Hikkim, the highest post office on earth.",
        location: "Kaza",
        accommodation: "Boutique Eco Hotel",
        meals: "Breakfast, Dinner",
        activities: ["High village postal drop", "Fossil hunting in Langza"],
      },
      {
        id: "d7",
        dayNumber: 7,
        title: "Kaza to Chandratal Lake",
        description: "Cross the magnificent Kunzum Pass at 4,590m. Hike down to the crescent-shaped sacred Chandratal lake at 4,300m. Camp under the Milky Way.",
        location: "Chandratal",
        accommodation: "Swiss Tents under the Stars",
        meals: "Breakfast, Dinner",
        activities: ["Kunzum Pass stupa walk", "Stargazing at Chandratal"],
      },
      {
        id: "d8",
        dayNumber: 8,
        title: "Chandratal to Atal Tunnel & Manali",
        description: "Drive through the rugged boulder tracks of Batal and Gramphu, crossing through the modern engineering marvel of Atal Tunnel to arrive in lush Manali.",
        location: "Manali",
        accommodation: "Cedar Lodge Manali",
        meals: "Breakfast, Dinner",
        activities: ["Atal Tunnel transit", "Celebratory dinner in Old Manali"],
      },
    ],
    departures: [
      {
        id: "dep-1",
        startDate: "2026-10-05T06:00:00Z",
        endDate: "2026-10-14T18:00:00Z",
        priceOverride: null,
        seatsTotal: 10,
        seatsBooked: 4,
        seatsAvailable: 6,
        status: "OPEN",
      },
      {
        id: "dep-2",
        startDate: "2026-10-18T06:00:00Z",
        endDate: "2026-10-27T18:00:00Z",
        priceOverride: null,
        seatsTotal: 10,
        seatsBooked: 2,
        seatsAvailable: 8,
        status: "OPEN",
      },
    ],
    pricingRules: [],
    media: [
      {
        id: "m1",
        url: "https://images.unsplash.com/photo-1581793745862-99fde7fa73d2?auto=format&fit=crop&w=1200&q=80",
        publicId: "spiti_key",
        altText: "Key Monastery perched on high Spiti hill",
        caption: "Key Monastery at 4,166m",
        isPrimary: true,
        sortOrder: 1,
      },
      {
        id: "m2",
        url: "https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?auto=format&fit=crop&w=1200&q=80",
        publicId: "spiti_chandratal",
        altText: "Chandratal Moon Lake azure reflections",
        caption: "Chandratal Lake sacred waters",
        isPrimary: false,
        sortOrder: 2,
      },
    ],
    faqs: [
      {
        id: "faq-1",
        question: "What fitness level is needed for this Spiti tour?",
        answer: "A moderate fitness level is recommended. Most journeys are by 4x4 vehicle with short day walks (1-2 hours) at altitude. We build gradual acclimatization into the route.",
        sortOrder: 1,
      },
      {
        id: "faq-2",
        question: "Is there mobile connectivity in Spiti Valley?",
        answer: "BSNL and Jio post-paid SIM cards receive coverage in Kaza and Tabo. Outside main towns, expect digital detox with no cellular signal.",
        sortOrder: 2,
      },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "tour-kinnaur-kailash",
    slug: "kinnaur-apple-valley-trail",
    title: "Kinnaur Apple Valley & Sacred Mountain Trail",
    travelStyle: "Cultural",
    durationDays: 6,
    minGroup: 2,
    maxGroup: 12,
    basePriceInr: 18500,
    summary:
      "A leisurely culture and landscape tour through the verdant valley of Kinnaur. Stay among blooming or harvest-ready apple orchards, visit Kamru fort, and gaze at Kinnaur Kailash.",
    highlights: [
      "Walk the ancient cedar paths of Sangla Valley",
      "Stay in boutique wooden cottages surrounded by orchards",
      "Visit Chitkul, the last tea shop of India",
      "Kamru Fort — seat of ancient Bushahr kingdom",
    ],
    inclusions: [
      "Comfortable SUV transfers from/to Shimla",
      "5 nights in heritage orchard homestays",
      "All breakfasts and traditional mountain dinners",
      "Dedicated local Kinnauri guide",
    ],
    exclusions: ["Personal expenses", "Flights to Chandigarh"],
    mapData: null,
    isPublished: true,
    isFeatured: true,
    sortOrder: 2,
    destination: {
      id: "dest-kinnaur",
      name: "Kinnaur Valley",
      slug: "kinnaur",
      region: "Lower Himalayas",
    },
    itineraryDays: [],
    departures: [],
    pricingRules: [],
    media: [
      {
        id: "m3",
        url: "https://images.unsplash.com/photo-1605649487212-47bdab064df8?auto=format&fit=crop&w=1200&q=80",
        publicId: "kinnaur_hero",
        altText: "Kinnaur wooden houses and apple orchards",
        caption: "Sangla Valley apple orchards",
        isPrimary: true,
        sortOrder: 1,
      },
    ],
    faqs: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "tour-shimla-heritage",
    slug: "shimla-colonial-ridge-walk",
    title: "Shimla Heritage & Deodar Forest Retreat",
    travelStyle: "Luxury",
    durationDays: 4,
    minGroup: 2,
    maxGroup: 8,
    basePriceInr: 14500,
    summary:
      "Immerse yourself in colonial history, high teas, Toy Train journeys, and forest bathing in cedar groves. Paired with fine mountain dining at Fayul Retreat.",
    highlights: [
      "Guided architectural heritage tour of British-era Shimla",
      "Kalka-Shimla UNESCO toy train experience",
      "Shinrin-yoku (forest bathing) in Mashobra sanctuary",
      "Sunset high tea overlooking snow-capped Shivaliks",
    ],
    inclusions: [
      "Luxury stay at Hotel Newlands / Fayul Retreat",
      "Toy Train tickets and station transfers",
      "Daily breakfast & bespoke dining",
      "Historian-guided walking tour",
    ],
    exclusions: ["Personal bar tabs", "Transit to Shimla"],
    mapData: null,
    isPublished: true,
    isFeatured: true,
    sortOrder: 3,
    destination: {
      id: "dest-shimla",
      name: "Shimla & Shivaliks",
      slug: "shimla",
      region: "Himachal Heartland",
    },
    itineraryDays: [],
    departures: [],
    pricingRules: [],
    media: [
      {
        id: "m4",
        url: "https://images.unsplash.com/photo-1597074866923-dc0589150358?auto=format&fit=crop&w=1200&q=80",
        publicId: "shimla_ridge",
        altText: "Shimla heritage ridge at sunset",
        caption: "The Ridge Shimla",
        isPrimary: true,
        sortOrder: 1,
      },
    ],
    faqs: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "tour-manali-lahaul-secret",
    slug: "lahaul-valley-glaciers-and-waterfalls",
    title: "Lahaul Hidden Valleys & High Passes Expedition",
    travelStyle: "Adventure",
    durationDays: 7,
    minGroup: 2,
    maxGroup: 8,
    basePriceInr: 22000,
    summary:
      "Explore the once-inaccessible valley of Lahaul. Sissu waterfalls, Keylong monasteries, high mountain passes, and tranquil glacial lakes.",
    highlights: [
      "Cross Atal Tunnel into the pristine Lahaul valley",
      "Walk to the foot of Sissu glacial waterfall",
      "Visit Gondhla ancient 7-storey wooden fort",
      "Camp near Deepak Tal & Suraj Tal lakes",
    ],
    inclusions: [
      "Private 4x4 expedition vehicle",
      "6 nights boutique stays and alpine camps",
      "All meals on tour",
      "Certified wilderness guides",
    ],
    exclusions: ["Flight tickets", "Beverages"],
    mapData: null,
    isPublished: true,
    isFeatured: true,
    sortOrder: 4,
    destination: {
      id: "dest-manali",
      name: "Manali & Lahaul",
      slug: "manali-lahaul",
      region: "Kullu & Pir Panjal",
    },
    itineraryDays: [],
    departures: [],
    pricingRules: [],
    media: [
      {
        id: "m5",
        url: "https://images.unsplash.com/photo-1571401835393-8c5f35328320?auto=format&fit=crop&w=1200&q=80",
        publicId: "lahaul_sissu",
        altText: "Lahaul valley mountain river and waterfall",
        caption: "Sissu waterfall and river valley",
        isPrimary: true,
        sortOrder: 1,
      },
    ],
    faqs: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
