import {
  DashboardOverviewData,
  AdminBooking,
  AdminRoom,
  HousekeepingTaskItem,
  GuestItem,
  CouponItem,
  ReviewItem,
} from "./admin.service";

export const MOCK_OVERVIEW_DATA: DashboardOverviewData = {
  kpis: {
    arrivalsToday: 4,
    departuresToday: 3,
    guestsInHouse: 18,
    occupancyRate: 86,
    totalRooms: 14,
    todayRevenue: 184500,
    monthlyRevenue: 3420000,
  },
  trends: [
    { date: "06 Sep", revenue: 142000, occupancy: 72 },
    { date: "07 Sep", revenue: 158000, occupancy: 79 },
    { date: "08 Sep", revenue: 175000, occupancy: 85 },
    { date: "09 Sep", revenue: 162000, occupancy: 80 },
    { date: "10 Sep", revenue: 189000, occupancy: 93 },
    { date: "11 Sep", revenue: 195000, occupancy: 95 },
    { date: "12 Sep", revenue: 184500, occupancy: 86 },
  ],
  recentBookings: [
    {
      id: "b-101",
      confirmationNumber: "NLS-902481",
      guestName: "Vikramaditya Singhania",
      roomName: "Governor's Heritage Suite",
      roomNumber: "101",
      checkIn: "2026-09-12",
      checkOut: "2026-09-15",
      total: 84000,
      status: "CONFIRMED",
    },
    {
      id: "b-102",
      confirmationNumber: "NLS-884129",
      guestName: "Ananya Deshmukh",
      roomName: "Cedar Ridge Chalet",
      roomNumber: "102",
      checkIn: "2026-09-11",
      checkOut: "2026-09-14",
      total: 67500,
      status: "CHECKED_IN",
    },
    {
      id: "b-103",
      confirmationNumber: "NLS-773912",
      guestName: "Rohan & Priya Mehra",
      roomName: "Pine Mist Valley Suite",
      roomNumber: "103",
      checkIn: "2026-09-10",
      checkOut: "2026-09-13",
      total: 54000,
      status: "CHECKED_IN",
    },
    {
      id: "b-104",
      confirmationNumber: "NLS-654820",
      guestName: "Devendra Rathore",
      roomName: "Viceroy Grand Presidential",
      roomNumber: "107",
      checkIn: "2026-09-09",
      checkOut: "2026-09-14",
      total: 175000,
      status: "CHECKED_IN",
    },
    {
      id: "b-105",
      confirmationNumber: "NLS-542190",
      guestName: "Siddharth Oberoi",
      roomName: "Colonial Fireside Suite",
      roomNumber: "105",
      checkIn: "2026-09-12",
      checkOut: "2026-09-15",
      total: 58500,
      status: "CONFIRMED",
    },
  ],
};

export const MOCK_ROOMS: AdminRoom[] = [
  {
    id: "r-101",
    roomNumber: "101",
    name: "Governor's Heritage Suite",
    status: "AVAILABLE",
    housekeepingStatus: "CLEAN",
    basePrice: 28000,
    weekendPrice: 32000,
    floor: 3,
    type: { id: "t-1", name: "Presidential Penthouse" },
    images: [{ url: "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1200&q=80", isPrimary: true }],
  },
  {
    id: "r-102",
    roomNumber: "102",
    name: "Cedar Ridge Chalet",
    status: "AVAILABLE",
    housekeepingStatus: "CLEAN",
    basePrice: 22500,
    weekendPrice: 26000,
    floor: 2,
    type: { id: "t-2", name: "Alpine Luxury Chalet" },
    images: [{ url: "https://images.unsplash.com/photo-1618773928121-c32242e63f39?auto=format&fit=crop&w=1200&q=80", isPrimary: true }],
  },
  {
    id: "r-103",
    roomNumber: "103",
    name: "Pine Mist Valley Suite",
    status: "AVAILABLE",
    housekeepingStatus: "CLEAN",
    basePrice: 18000,
    weekendPrice: 21000,
    floor: 2,
    type: { id: "t-3", name: "Valley View Deluxe" },
    images: [{ url: "https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=1200&q=80", isPrimary: true }],
  },
  {
    id: "r-104",
    roomNumber: "104",
    name: "Himalayan Panorama Chalet",
    status: "AVAILABLE",
    housekeepingStatus: "INSPECTION",
    basePrice: 24000,
    weekendPrice: 28000,
    floor: 3,
    type: { id: "t-2", name: "Alpine Luxury Chalet" },
    images: [{ url: "https://images.unsplash.com/photo-1591088398332-8a7791972843?auto=format&fit=crop&w=1200&q=80", isPrimary: true }],
  },
  {
    id: "r-105",
    roomNumber: "105",
    name: "Colonial Fireside Suite",
    status: "AVAILABLE",
    housekeepingStatus: "CLEAN",
    basePrice: 19500,
    weekendPrice: 23000,
    floor: 1,
    type: { id: "t-4", name: "Heritage Fireplace Suite" },
    images: [{ url: "https://images.unsplash.com/photo-1613545325278-f24b0cae1224?auto=format&fit=crop&w=1200&q=80", isPrimary: true }],
  },
  {
    id: "r-106",
    roomNumber: "106",
    name: "Deodar Forest Haven",
    status: "AVAILABLE",
    housekeepingStatus: "CLEANING",
    basePrice: 16000,
    weekendPrice: 18500,
    floor: 1,
    type: { id: "t-5", name: "Forest Glade Room" },
    images: [{ url: "https://images.unsplash.com/photo-1566665797739-1674de7a421a?auto=format&fit=crop&w=1200&q=80", isPrimary: true }],
  },
  {
    id: "r-107",
    roomNumber: "107",
    name: "Viceroy Grand Presidential",
    status: "AVAILABLE",
    housekeepingStatus: "CLEAN",
    basePrice: 35000,
    weekendPrice: 42000,
    floor: 3,
    type: { id: "t-1", name: "Presidential Penthouse" },
    images: [{ url: "https://images.unsplash.com/photo-1578683010236-d716f9a3f461?auto=format&fit=crop&w=1200&q=80", isPrimary: true }],
  },
  {
    id: "r-108",
    roomNumber: "108",
    name: "Misty Glade Studio",
    status: "AVAILABLE",
    housekeepingStatus: "DIRTY",
    basePrice: 14500,
    weekendPrice: 16500,
    floor: 2,
    type: { id: "t-6", name: "Executive Studio" },
    images: [{ url: "https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?auto=format&fit=crop&w=1200&q=80", isPrimary: true }],
  },
  {
    id: "r-109",
    roomNumber: "109",
    name: "Shimla Ridge Royal Suite",
    status: "AVAILABLE",
    housekeepingStatus: "CLEAN",
    basePrice: 26000,
    weekendPrice: 30000,
    floor: 2,
    type: { id: "t-4", name: "Heritage Fireplace Suite" },
    images: [{ url: "https://images.unsplash.com/photo-1540518614846-7ede433c4ef0?auto=format&fit=crop&w=1200&q=80", isPrimary: true }],
  },
  {
    id: "r-110",
    roomNumber: "110",
    name: "Alpine Stargazer Loft",
    status: "AVAILABLE",
    housekeepingStatus: "CLEAN",
    basePrice: 21000,
    weekendPrice: 24500,
    floor: 3,
    type: { id: "t-2", name: "Alpine Luxury Chalet" },
    images: [{ url: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1200&q=80", isPrimary: true }],
  },
  {
    id: "r-111",
    roomNumber: "111",
    name: "Orchard View Sanctuary",
    status: "AVAILABLE",
    housekeepingStatus: "CLEAN",
    basePrice: 17500,
    weekendPrice: 20000,
    floor: 1,
    type: { id: "t-5", name: "Forest Glade Room" },
    images: [{ url: "https://images.unsplash.com/photo-1590490359854-dfba19688d70?auto=format&fit=crop&w=1200&q=80", isPrimary: true }],
  },
  {
    id: "r-112",
    roomNumber: "112",
    name: "The 1928 Heritage Chamber",
    status: "MAINTENANCE",
    housekeepingStatus: "INSPECTION",
    basePrice: 20000,
    weekendPrice: 23500,
    floor: 1,
    type: { id: "t-4", name: "Heritage Fireplace Suite" },
    images: [{ url: "https://images.unsplash.com/photo-1618773928121-c32242e63f39?auto=format&fit=crop&w=1200&q=80", isPrimary: true }],
  },
  {
    id: "r-113",
    roomNumber: "113",
    name: "Tara Devi Sanctuary",
    status: "AVAILABLE",
    housekeepingStatus: "CLEAN",
    basePrice: 19000,
    weekendPrice: 22000,
    floor: 2,
    type: { id: "t-3", name: "Valley View Deluxe" },
    images: [{ url: "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1200&q=80", isPrimary: true }],
  },
  {
    id: "r-114",
    roomNumber: "114",
    name: "Snowline Whispering Pines",
    status: "AVAILABLE",
    housekeepingStatus: "CLEAN",
    basePrice: 23500,
    weekendPrice: 27000,
    floor: 3,
    type: { id: "t-2", name: "Alpine Luxury Chalet" },
    images: [{ url: "https://images.unsplash.com/photo-1578683010236-d716f9a3f461?auto=format&fit=crop&w=1200&q=80", isPrimary: true }],
  },
];

export const MOCK_BOOKINGS: AdminBooking[] = [
  {
    id: "b-101",
    confirmationNumber: "NLS-902481",
    checkIn: "2026-09-12",
    checkOut: "2026-09-15",
    adults: 2,
    children: 0,
    status: "CONFIRMED",
    total: 84000,
    guestName: "Vikramaditya Singhania",
    guestEmail: "v.singhania@heritageholdings.in",
    guestPhone: "+91 98110 44291",
    room: {
      name: "Governor's Heritage Suite",
      roomNumber: "101",
      type: { name: "Presidential Penthouse" },
    },
    user: {
      name: "Vikramaditya Singhania",
      email: "v.singhania@heritageholdings.in",
      phone: "+91 98110 44291",
    },
  },
  {
    id: "b-102",
    confirmationNumber: "NLS-884129",
    checkIn: "2026-09-11",
    checkOut: "2026-09-14",
    adults: 2,
    children: 1,
    status: "CHECKED_IN",
    total: 67500,
    guestName: "Ananya Deshmukh",
    guestEmail: "ananya.deshmukh@gmail.com",
    guestPhone: "+91 98201 88342",
    room: {
      name: "Cedar Ridge Chalet",
      roomNumber: "102",
      type: { name: "Alpine Luxury Chalet" },
    },
    user: {
      name: "Ananya Deshmukh",
      email: "ananya.deshmukh@gmail.com",
      phone: "+91 98201 88342",
    },
  },
  {
    id: "b-103",
    confirmationNumber: "NLS-773912",
    checkIn: "2026-09-10",
    checkOut: "2026-09-13",
    adults: 2,
    children: 0,
    status: "CHECKED_IN",
    total: 54000,
    guestName: "Rohan & Priya Mehra",
    guestEmail: "rohan.mehra@techventures.co",
    guestPhone: "+91 99100 55219",
    room: {
      name: "Pine Mist Valley Suite",
      roomNumber: "103",
      type: { name: "Valley View Deluxe" },
    },
    user: {
      name: "Rohan Mehra",
      email: "rohan.mehra@techventures.co",
      phone: "+91 99100 55219",
    },
  },
  {
    id: "b-104",
    confirmationNumber: "NLS-654820",
    checkIn: "2026-09-09",
    checkOut: "2026-09-14",
    adults: 2,
    children: 2,
    status: "CHECKED_IN",
    total: 175000,
    guestName: "Devendra Rathore",
    guestEmail: "rathore.devendra@royalmarwar.in",
    guestPhone: "+91 94140 12890",
    room: {
      name: "Viceroy Grand Presidential",
      roomNumber: "107",
      type: { name: "Presidential Penthouse" },
    },
    user: {
      name: "Devendra Rathore",
      email: "rathore.devendra@royalmarwar.in",
      phone: "+91 94140 12890",
    },
  },
  {
    id: "b-105",
    confirmationNumber: "NLS-542190",
    checkIn: "2026-09-12",
    checkOut: "2026-09-15",
    adults: 2,
    children: 0,
    status: "CONFIRMED",
    total: 58500,
    guestName: "Siddharth Oberoi",
    guestEmail: "siddharth.oberoi@globaladvisors.com",
    guestPhone: "+91 98450 77123",
    room: {
      name: "Colonial Fireside Suite",
      roomNumber: "105",
      type: { name: "Heritage Fireplace Suite" },
    },
    user: {
      name: "Siddharth Oberoi",
      email: "siddharth.oberoi@globaladvisors.com",
      phone: "+91 98450 77123",
    },
  },
  {
    id: "b-106",
    confirmationNumber: "NLS-439812",
    checkIn: "2026-09-13",
    checkOut: "2026-09-16",
    adults: 2,
    children: 0,
    status: "CONFIRMED",
    total: 78000,
    guestName: "Meera Kapoor",
    guestEmail: "meera.kapoor@studioarc.in",
    guestPhone: "+91 98190 66451",
    room: {
      name: "Shimla Ridge Royal Suite",
      roomNumber: "109",
      type: { name: "Heritage Fireplace Suite" },
    },
    user: {
      name: "Meera Kapoor",
      email: "meera.kapoor@studioarc.in",
      phone: "+91 98190 66451",
    },
  },
  {
    id: "b-107",
    confirmationNumber: "NLS-321098",
    checkIn: "2026-09-10",
    checkOut: "2026-09-12",
    adults: 1,
    children: 0,
    status: "CHECKED_OUT",
    total: 35000,
    guestName: "Arjun Nambiar",
    guestEmail: "arjun.nambiar@apexlegal.org",
    guestPhone: "+91 97411 99023",
    room: {
      name: "Orchard View Sanctuary",
      roomNumber: "111",
      type: { name: "Forest Glade Room" },
    },
    user: {
      name: "Arjun Nambiar",
      email: "arjun.nambiar@apexlegal.org",
      phone: "+91 97411 99023",
    },
  },
  {
    id: "b-108",
    confirmationNumber: "NLS-219874",
    checkIn: "2026-09-11",
    checkOut: "2026-09-14",
    adults: 2,
    children: 0,
    status: "CHECKED_IN",
    total: 70500,
    guestName: "Dr. Kabir Sen",
    guestEmail: "kabir.sen@aiims.edu",
    guestPhone: "+91 98711 33452",
    room: {
      name: "Snowline Whispering Pines",
      roomNumber: "114",
      type: { name: "Alpine Luxury Chalet" },
    },
    user: {
      name: "Dr. Kabir Sen",
      email: "kabir.sen@aiims.edu",
      phone: "+91 98711 33452",
    },
  },
  {
    id: "b-109",
    confirmationNumber: "NLS-198453",
    checkIn: "2026-09-08",
    checkOut: "2026-09-11",
    adults: 2,
    children: 0,
    status: "COMPLETED",
    total: 63000,
    guestName: "Tanvi Verma",
    guestEmail: "tanvi.verma@delhicapital.com",
    guestPhone: "+91 98101 22891",
    room: {
      name: "Alpine Stargazer Loft",
      roomNumber: "110",
      type: { name: "Alpine Luxury Chalet" },
    },
    user: {
      name: "Tanvi Verma",
      email: "tanvi.verma@delhicapital.com",
      phone: "+91 98101 22891",
    },
  },
  {
    id: "b-110",
    confirmationNumber: "NLS-108234",
    checkIn: "2026-09-14",
    checkOut: "2026-09-16",
    adults: 2,
    children: 0,
    status: "CANCELLED",
    total: 48000,
    guestName: "Aditya Birla",
    guestEmail: "aditya.b@venturecorp.in",
    guestPhone: "+91 98200 44551",
    room: {
      name: "Himalayan Panorama Chalet",
      roomNumber: "104",
      type: { name: "Alpine Luxury Chalet" },
    },
    user: {
      name: "Aditya Birla",
      email: "aditya.b@venturecorp.in",
      phone: "+91 98200 44551",
    },
  },
];

export const MOCK_HOUSEKEEPING_TASKS: HousekeepingTaskItem[] = [
  {
    id: "hk-1",
    roomId: "r-101",
    task: "Turnover deep clean & fireplace aromatic cedar logs restock",
    assignedTo: "Ramesh Thakur",
    priority: "HIGH",
    status: "IN_PROGRESS",
    notes: "VIP check-in scheduled for 2:00 PM today. Ensure goose-feather pillows fluffed.",
    room: { roomNumber: "101", name: "Governor's Heritage Suite" },
    createdAt: "2026-09-12T08:30:00Z",
  },
  {
    id: "hk-2",
    roomId: "r-108",
    task: "Post-checkout sanitization & organic herbal toiletry replenish",
    assignedTo: "Sunita Devi",
    priority: "HIGH",
    status: "PENDING",
    notes: "Full linen strip and steam clean requested.",
    room: { roomNumber: "108", name: "Misty Glade Studio" },
    createdAt: "2026-09-12T09:15:00Z",
  },
  {
    id: "hk-3",
    roomId: "r-112",
    task: "Cast-iron radiator servicing & vintage brass polish",
    assignedTo: "Rajesh Verma",
    priority: "NORMAL",
    status: "IN_PROGRESS",
    notes: "Engineering team checking bedroom radiator pressure valves.",
    room: { roomNumber: "112", name: "The 1928 Heritage Chamber" },
    createdAt: "2026-09-12T07:45:00Z",
  },
  {
    id: "hk-4",
    roomId: "r-107",
    task: "Private sun terrace sweep & fresh mountain orchid arrangement",
    assignedTo: "Priya Sharma",
    priority: "NORMAL",
    status: "COMPLETED",
    notes: "Terrace cleared and high-tea table staged with fine porcelain.",
    room: { roomNumber: "107", name: "Viceroy Grand Presidential" },
    createdAt: "2026-09-12T06:30:00Z",
  },
  {
    id: "hk-5",
    roomId: "r-106",
    task: "Deodar forest balcony glass washing and pine needle sweep",
    assignedTo: "Amit Negi",
    priority: "NORMAL",
    status: "IN_PROGRESS",
    notes: "Morning dew cleanup completed on deck railing.",
    room: { roomNumber: "106", name: "Deodar Forest Haven" },
    createdAt: "2026-09-12T10:00:00Z",
  },
];

export const MOCK_GUESTS: GuestItem[] = [
  {
    id: "g-1",
    name: "Vikramaditya Singhania",
    email: "v.singhania@heritageholdings.in",
    phone: "+91 98110 44291",
    city: "New Delhi",
    state: "Delhi",
    country: "India",
    createdAt: "2025-11-14T10:00:00Z",
    _count: { bookings: 4, reviews: 3 },
  },
  {
    id: "g-2",
    name: "Ananya Deshmukh",
    email: "ananya.deshmukh@gmail.com",
    phone: "+91 98201 88342",
    city: "Mumbai",
    state: "Maharashtra",
    country: "India",
    createdAt: "2026-01-20T14:30:00Z",
    _count: { bookings: 2, reviews: 2 },
  },
  {
    id: "g-3",
    name: "Devendra Rathore",
    email: "rathore.devendra@royalmarwar.in",
    phone: "+91 94140 12890",
    city: "Jaipur",
    state: "Rajasthan",
    country: "India",
    createdAt: "2025-08-04T09:15:00Z",
    _count: { bookings: 5, reviews: 4 },
  },
  {
    id: "g-4",
    name: "Rohan Mehra",
    email: "rohan.mehra@techventures.co",
    phone: "+91 99100 55219",
    city: "Bengaluru",
    state: "Karnataka",
    country: "India",
    createdAt: "2026-03-11T12:00:00Z",
    _count: { bookings: 3, reviews: 2 },
  },
  {
    id: "g-5",
    name: "Siddharth Oberoi",
    email: "siddharth.oberoi@globaladvisors.com",
    phone: "+91 98450 77123",
    city: "Chandigarh",
    state: "Punjab",
    country: "India",
    createdAt: "2026-02-18T16:20:00Z",
    _count: { bookings: 2, reviews: 1 },
  },
  {
    id: "g-6",
    name: "Meera Kapoor",
    email: "meera.kapoor@studioarc.in",
    phone: "+91 98190 66451",
    city: "Mumbai",
    state: "Maharashtra",
    country: "India",
    createdAt: "2026-04-05T11:45:00Z",
    _count: { bookings: 3, reviews: 3 },
  },
  {
    id: "g-7",
    name: "Dr. Kabir Sen",
    email: "kabir.sen@aiims.edu",
    phone: "+91 98711 33452",
    city: "Kolkata",
    state: "West Bengal",
    country: "India",
    createdAt: "2025-12-02T15:10:00Z",
    _count: { bookings: 4, reviews: 2 },
  },
  {
    id: "g-8",
    name: "Lord James Alistair",
    email: "j.alistair@highlandsoxford.co.uk",
    phone: "+44 7700 900142",
    city: "London",
    state: "Greater London",
    country: "United Kingdom",
    createdAt: "2025-07-19T08:00:00Z",
    _count: { bookings: 6, reviews: 5 },
  },
];

export const MOCK_COUPONS: CouponItem[] = [
  {
    id: "cp-1",
    code: "HIMALAYANWINTER",
    discountType: "PERCENTAGE",
    value: 20,
    minBookingAmount: 30000,
    startDate: "2026-09-01",
    endDate: "2026-12-31",
    usageCount: 42,
    isActive: true,
  },
  {
    id: "cp-2",
    code: "HONEYMOON25",
    discountType: "PERCENTAGE",
    value: 25,
    minBookingAmount: 50000,
    startDate: "2026-08-15",
    endDate: "2026-11-30",
    usageCount: 18,
    isActive: true,
  },
  {
    id: "cp-3",
    code: "EARLYBIRD10",
    discountType: "PERCENTAGE",
    value: 10,
    minBookingAmount: 20000,
    startDate: "2026-01-01",
    endDate: "2026-12-31",
    usageCount: 124,
    isActive: true,
  },
  {
    id: "cp-4",
    code: "ESTATEESCAPE",
    discountType: "FIXED",
    value: 5000,
    minBookingAmount: 40000,
    startDate: "2026-07-01",
    endDate: "2026-10-31",
    usageCount: 31,
    isActive: true,
  },
];

export const MOCK_REVIEWS: ReviewItem[] = [
  {
    id: "rev-1",
    overallRating: 5,
    cleanlinessRating: 5,
    serviceRating: 5,
    comment:
      "A quintessential colonial sanctuary above the clouds. The Governor's Suite fireplace was crackling upon our arrival, and the view of Tara Devi peak at dawn from the balcony was simply unforgettable. The staff's discretion and warmth are world-class.",
    status: "APPROVED",
    adminReply:
      "Honoured to have hosted you at Hotel Newlands, Mr. Singhania. We look forward to welcoming you back for the winter snowfall season.",
    createdAt: "2026-09-05T14:20:00Z",
    user: {
      name: "Vikramaditya Singhania",
      email: "v.singhania@heritageholdings.in",
    },
    booking: {
      confirmationNumber: "NLS-902481",
      room: {
        name: "Governor's Heritage Suite",
        roomNumber: "101",
      },
    },
  },
  {
    id: "rev-2",
    overallRating: 5,
    cleanlinessRating: 5,
    serviceRating: 5,
    comment:
      "The Cedar Hearth restaurant is a masterclass in Himachali gastronomy. The pan-seared river trout and wild blackberry crumble served by our fireplace was the culinary highlight of our year.",
    status: "APPROVED",
    adminReply:
      "Thank you, Ananya. Chef Negi and the entire culinary brigade are delighted that you enjoyed our artisanal estate dining.",
    createdAt: "2026-09-02T18:45:00Z",
    user: {
      name: "Ananya Deshmukh",
      email: "ananya.deshmukh@gmail.com",
    },
    booking: {
      confirmationNumber: "NLS-884129",
      room: {
        name: "Cedar Ridge Chalet",
        roomNumber: "102",
      },
    },
  },
  {
    id: "rev-3",
    overallRating: 5,
    cleanlinessRating: 5,
    serviceRating: 5,
    comment:
      "Having stayed at luxury heritage properties across Scotland and Switzerland, Hotel Newlands Shimla stands shoulder to shoulder with the finest alpine estates. Impeccable attention to period detail.",
    status: "APPROVED",
    adminReply:
      "We are deeply grateful for your high praise, Lord Alistair. Preserving the 1928 heritage while providing contemporary luxury is our guiding ethos.",
    createdAt: "2026-08-28T09:10:00Z",
    user: {
      name: "Lord James Alistair",
      email: "j.alistair@highlandsoxford.co.uk",
    },
    booking: {
      confirmationNumber: "NLS-701294",
      room: {
        name: "Viceroy Grand Presidential",
        roomNumber: "107",
      },
    },
  },
  {
    id: "rev-4",
    overallRating: 4,
    cleanlinessRating: 5,
    serviceRating: 4,
    comment:
      "Exquisite stay in the Pine Mist Valley Suite. Peaceful, secluded, and serene. Room service during peak evening hours took approximately 35 minutes, but the food quality more than compensated.",
    status: "PENDING",
    createdAt: "2026-09-11T20:15:00Z",
    user: {
      name: "Rohan Mehra",
      email: "rohan.mehra@techventures.co",
    },
    booking: {
      confirmationNumber: "NLS-773912",
      room: {
        name: "Pine Mist Valley Suite",
        roomNumber: "103",
      },
    },
  },
];

export const MOCK_FOOD_ORDERS = [
  {
    id: "fo-1",
    orderNumber: "ORD-4821",
    roomNumber: "101",
    deliveryType: "ROOM",
    status: "PREPARING",
    subtotal: 3285,
    tax: 165,
    total: 3450,
    specialNotes: "Extra clarified butter on pilaf, please bring fine bone china.",
    createdAt: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    user: { name: "Vikramaditya Singhania", phone: "+91 98110 44291" },
    items: [
      {
        id: "item-1",
        quantity: 2,
        unitPrice: 1100,
        total: 2200,
        specialInstructions: "Fresh Himalayan trout pan-seared with almond butter",
        foodItem: { id: "fi-1", name: "Pan-Seared Himalayan River Trout", isVeg: false },
      },
      {
        id: "item-2",
        quantity: 1,
        unitPrice: 485,
        total: 485,
        specialInstructions: "Walnuts toasted crisp",
        foodItem: { id: "fi-2", name: "Saffron & Wild Walnut Pilaf", isVeg: true },
      },
      {
        id: "item-3",
        quantity: 2,
        unitPrice: 300,
        total: 600,
        specialInstructions: "Served warm with vanilla bean custard",
        foodItem: { id: "fi-3", name: "Wild Blackberry Alpine Crumble", isVeg: true },
      },
    ],
  },
  {
    id: "fo-2",
    orderNumber: "ORD-4820",
    roomNumber: "107",
    deliveryType: "ROOM",
    status: "READY",
    subtotal: 2076,
    tax: 104,
    total: 2180,
    specialNotes: "Deliver immediately to Viceroy private dining terrace.",
    createdAt: new Date(Date.now() - 35 * 60 * 1000).toISOString(),
    user: { name: "Devendra Rathore", phone: "+91 94140 12890" },
    items: [
      {
        id: "item-4",
        quantity: 1,
        unitPrice: 750,
        total: 750,
        specialInstructions: "Mild spice level",
        foodItem: { id: "fi-4", name: "The Cedar Hearth Kadhai Paneer", isVeg: true },
      },
      {
        id: "item-5",
        quantity: 2,
        unitPrice: 280,
        total: 560,
        specialInstructions: "Crisp and hot from tandoor",
        foodItem: { id: "fi-5", name: "Truffle & Roasted Garlic Naan", isVeg: true },
      },
      {
        id: "item-6",
        quantity: 2,
        unitPrice: 383,
        total: 766,
        specialInstructions: "Brewed with mountain cardamom",
        foodItem: { id: "fi-6", name: "Estate Spiced Kangra Valley Chai", isVeg: true },
      },
    ],
  },
  {
    id: "fo-3",
    orderNumber: "ORD-4819",
    roomNumber: "103",
    deliveryType: "ROOM",
    status: "CONFIRMED",
    subtotal: 1190,
    tax: 60,
    total: 1250,
    specialNotes: "Gluten-free preferences noted.",
    createdAt: new Date(Date.now() - 8 * 60 * 1000).toISOString(),
    user: { name: "Rohan Mehra", phone: "+91 99100 55219" },
    items: [
      {
        id: "item-7",
        quantity: 2,
        unitPrice: 420,
        total: 840,
        specialInstructions: "Velvety texture with herb croutons on the side",
        foodItem: { id: "fi-7", name: "Wild Porcini & Pine Mushroom Velouté", isVeg: true },
      },
      {
        id: "item-8",
        quantity: 1,
        unitPrice: 350,
        total: 350,
        specialInstructions: "Cultured mountain butter",
        foodItem: { id: "fi-8", name: "Artisanal Sourdough & Herb Butter", isVeg: true },
      },
    ],
  },
  {
    id: "fo-4",
    orderNumber: "ORD-4818",
    roomNumber: "102",
    deliveryType: "ROOM",
    status: "DELIVERED",
    subtotal: 3905,
    tax: 195,
    total: 4100,
    specialNotes: "Guest enjoyed dinner fireside.",
    createdAt: new Date(Date.now() - 75 * 60 * 1000).toISOString(),
    user: { name: "Ananya Deshmukh", phone: "+91 98201 88342" },
    items: [
      {
        id: "item-9",
        quantity: 2,
        unitPrice: 1250,
        total: 2500,
        specialInstructions: "Slow-cooked on embers with aromatic whole spices",
        foodItem: { id: "fi-9", name: "Himachali Gosht Rogan Josh", isVeg: false },
      },
      {
        id: "item-10",
        quantity: 2,
        unitPrice: 350,
        total: 700,
        specialInstructions: "Steamed Dehradun basmati",
        foodItem: { id: "fi-10", name: "Aged Basmati Rice", isVeg: true },
      },
      {
        id: "item-11",
        quantity: 2,
        unitPrice: 352,
        total: 705,
        specialInstructions: "Garnished with toasted pistachios",
        foodItem: { id: "fi-11", name: "Spiced Mountain Fig Kulfi", isVeg: true },
      },
    ],
  },
  {
    id: "fo-5",
    orderNumber: "ORD-4817",
    roomNumber: "105",
    deliveryType: "ROOM",
    status: "DELIVERED",
    subtotal: 1800,
    tax: 90,
    total: 1890,
    createdAt: new Date(Date.now() - 120 * 60 * 1000).toISOString(),
    user: { name: "Siddharth Oberoi", phone: "+91 98450 77123" },
    items: [
      {
        id: "item-12",
        quantity: 1,
        unitPrice: 650,
        total: 650,
        specialInstructions: "Smoked poultry and aged cheddar",
        foodItem: { id: "fi-12", name: "Heritage Estate Club Sandwich", isVeg: false },
      },
      {
        id: "item-13",
        quantity: 2,
        unitPrice: 425,
        total: 850,
        specialInstructions: "Warm cinnamon glaze",
        foodItem: { id: "fi-13", name: "Warm Shimla Apple Strudel", isVeg: true },
      },
      {
        id: "item-14",
        quantity: 1,
        unitPrice: 300,
        total: 300,
        foodItem: { id: "fi-14", name: "Artisanal Hot Cocoa with Marshmallows", isVeg: true },
      },
    ],
  },
];

export const MOCK_FINANCE_SUMMARY = {
  totalCapturedPayments: 4285600,
  totalRoomRevenue: 3420000,
  totalRoomTax: 615600,
  totalFoodRevenue: 238000,
  totalFoodTax: 12000,
  totalTaxCollected: 627600,
  totalGrossRevenue: 4285600,
  taxRules: [
    {
      type: "GST_ROOM_LUXURY",
      name: "GST on Room Tariff (>₹7500)",
      rate: 18,
      applicableOn: "Luxury Suite Lodging Accommodations",
    },
    {
      type: "GST_ROOM_STANDARD",
      name: "GST on Room Tariff (₹2500 - ₹7500)",
      rate: 12,
      applicableOn: "Standard Mountain Suite Lodging",
    },
    {
      type: "GST_DINING",
      name: "GST on Dining & Food Services",
      rate: 5,
      applicableOn: "In-Room Dining & Cedar Hearth Restaurant",
    },
  ],
  recentInvoices: [
    { id: "inv-1", invoiceNumber: "NLS/2026/000008", total: 84000, tax: 12813, issuedAt: "2026-09-12T11:30:00Z", status: "PAID" },
    { id: "inv-2", invoiceNumber: "NLS/2026/000007", total: 67500, tax: 10296, issuedAt: "2026-09-11T14:15:00Z", status: "PAID" },
    { id: "inv-3", invoiceNumber: "NLS/2026/000006", total: 54000, tax: 8237, issuedAt: "2026-09-10T16:00:00Z", status: "PAID" },
    { id: "inv-4", invoiceNumber: "NLS/2026/000005", total: 175000, tax: 26694, issuedAt: "2026-09-09T18:20:00Z", status: "PAID" },
    { id: "inv-5", invoiceNumber: "NLS/2026/000004", total: 58500, tax: 8923, issuedAt: "2026-09-08T12:40:00Z", status: "PAID" },
    { id: "inv-6", invoiceNumber: "NLS/2026/000003", total: 78000, tax: 11898, issuedAt: "2026-09-07T10:15:00Z", status: "PAID" },
    { id: "inv-7", invoiceNumber: "NLS/2026/000002", total: 35000, tax: 5338, issuedAt: "2026-09-06T15:50:00Z", status: "PAID" },
    { id: "inv-8", invoiceNumber: "NLS/2026/000001", total: 70500, tax: 10754, issuedAt: "2026-09-05T09:00:00Z", status: "PAID" },
  ],
};

export const MOCK_ADVANCED_ANALYTICS = {
  kpis: {
    adr: 22450,
    revPar: 19307,
    occupancyPercent: 86,
    cancellationRate: 3.2,
    totalRevenue: 3420000,
    totalBookings: 142,
    completedBookings: 128,
  },
  trends: [
    { date: "14 Aug", revenue: 110000, occupancy: 68, adr: 21500 },
    { date: "17 Aug", revenue: 135000, occupancy: 74, adr: 21800 },
    { date: "20 Aug", revenue: 148000, occupancy: 78, adr: 22000 },
    { date: "23 Aug", revenue: 165000, occupancy: 82, adr: 22300 },
    { date: "26 Aug", revenue: 172000, occupancy: 85, adr: 22400 },
    { date: "29 Aug", revenue: 185000, occupancy: 89, adr: 22700 },
    { date: "01 Sep", revenue: 160000, occupancy: 80, adr: 22100 },
    { date: "04 Sep", revenue: 178000, occupancy: 84, adr: 22400 },
    { date: "07 Sep", revenue: 192000, occupancy: 91, adr: 22800 },
    { date: "10 Sep", revenue: 195000, occupancy: 95, adr: 22900 },
    { date: "12 Sep", revenue: 184500, occupancy: 86, adr: 22450 },
  ],
};

export const MOCK_CMS_PAGES: Record<string, any> = {
  home: {
    hero: {
      title: "Heritage Himalayan Retreat Above The Pines",
      subtitle: "Est. 1928 • Colonial Elegance, Pine-Scented Ridge Vistas & Fireside Luxury in Shimla",
    },
    seo: {
      title: "Hotel Newlands Shimla | Luxury Heritage Mountain Resort",
      description: "Experience bespoke colonial hospitality at Hotel Newlands, nestled amidst deodar woods on Shimla's historic mountain ridge.",
    },
  },
  about: {
    hero: {
      title: "The Legacy of 1928: A Century of Himalayan Grace",
      subtitle: "Originally commissioned as an estate retreat for governors, now meticulously restored for the discerning traveler.",
    },
    seo: {
      title: "About Hotel Newlands | Colonial Architecture & Heritage",
      description: "Discover the 1928 heritage story, colonial architecture, and restoration of Shimla's premier mountain estate.",
    },
  },
  dining: {
    hero: {
      title: "The Cedar Hearth: Epicurean Mountain Gastronomy",
      subtitle: "Wood-fired artisanal cuisine celebrating Himachali heirloom spices and wild orchard bounties.",
    },
    seo: {
      title: "The Cedar Hearth Dining | Fine Cuisine at Hotel Newlands",
      description: "Savor gourmet Himachali delicacies, wild trout, and colonial high teas crafted with fresh alpine ingredients.",
    },
  },
  experiences: {
    hero: {
      title: "Curated Mountain Pursuits & Fireside Serenades",
      subtitle: "From sunrise ridge walks through ancient deodars to private astronomy stargazing sessions.",
    },
    seo: {
      title: "Himalayan Experiences & Pursuits | Hotel Newlands Shimla",
      description: "Explore curated outdoor activities, pine forest bathing, guided colonial walks, and ridge high tea.",
    },
  },
  offers: {
    hero: {
      title: "Exclusive Mountain Sojourns & Seasonal Escapes",
      subtitle: "Curated winter snowfall, romance packages, and long-stay privileges for our esteemed guests.",
    },
    seo: {
      title: "Special Offers & Retreat Packages | Hotel Newlands",
      description: "Reserve luxury Shimla holiday packages with complimentary estate dining, airport transfers, and spa inclusions.",
    },
  },
};
